# Sotalol -- leave title blank below
#+TITLE:  
#+AUTHOR:    David Mann
#+EMAIL:     mannd@epstudiossoftware.com
#+DATE:      [2015-03-06 Fri]
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
* Note
- Sotalol should only be prescribed by physicians experienced in its use.  This outline is no substitute for a comprehensive familiarity with the drug and its packaging information.
- Also note that packaging information is different for Betapace and Betapace AF, though information for both forms of sotalol are given here.
* Dosage and administration
** Ventricular and supraventricular arrhythmias (Betapace)
- 80 mg PO q12hr initially; increase PRN to 120-160 mg q12hr (2-3 days between increments).
** Refractory life-threatening arrhythmias (Betapace)
- 80 mg PO q12hr initially; increase PRN to 120-160 mg q12hr (2-3 days between increments) to 160-320 mg/day divided q8-12hr; up to 480-640 mg/day may be required if benefits outweigh increased adverse effects.
** Atrial fibrillation or flutter (Betapace AF)
- 80 mg PO q12hr; increase PRN to 120-160 mg q12hr.
** Dosing modifications for renal failure (atrial fibrillation/flutter)
| CrCl            | Dose            |
|-----------------+-----------------|
| >60 mL/min      | give q12hr      |
| 40 to 60 mL/min | give once daily |
| <40 mL/min      | Contraindicated |
** Dosing modifications for renal failure (ventricular arrhythmias)
| CrCl            | Dose            |
|-----------------+-----------------|
| >60 mL/min      | give q12hr      |
| 30 to 59 mL/min | give once daily |
| <40 mL/min      | Contraindicated |
** Monitor QT interval during initiation of therapy
- Baseline QT interval must be ≤450 msec (or JT <330 msec) to start therapy.
- Monitor QT interval 2-4 hrs after each dose.
- If the QT interval prolongs to 500 msec or greater the dose must be reduced or the drug discontinued.
* Dosage forms and strengths
- Tablets
  - 80 mg
  - 120 mg 
  - 160 mg
  - 240 mg
* Warnings
- Sotalol can cause serious ventricular arrhythmias, primarily Torsade de Pointes (TdP) type ventricular tachycardia, a polymorphic ventricular tachycardia associated with QT interval prolongation. QT prolongation is directly related to sotalol dose.  Factors such as reduced CrCl, female gender, and larger doses increase the risk of TdP.  The risk of TdP can be reduced by adjustment of the sotalol dose according to CrCl and by monitoring the ECG for excessive increases in the QT interval.
- Hospitalize patient at least 3 days while on maintenance dose in facility that provides cardiac resuscitation, continuous ECG monitoring, and estimated CrCl.
- Calculate CrCl before initiating sotalol therapy.
- Measure QT interval before initiating sotalol therapy.
* Contraindications
- Sinus bradycardia (<50 bpm during waking hours).
- Sick sinus syndrome or 2nd or 3rd degree AV block unless functioning pacemaker is present.
- Congenital or acquired long QT syndromes.
- Baseline QT interval >450 msec.
- Cardiogenic shock, uncontrolled heart failure.
- Hypokalemia (<4 meq/L).
- CrCl <40 mL/min.
- Bronchial asthma.
- Previous hypersensitivity to sotalol.
* Adverse reactions
- 1-2% incidence of proarrhythmia and Torsade de Pointes with potentially fatal ventricular arrhythmias.
- >10% include dyspnea, dizziness, fatigue, bradycardia, chest pain, palpitations, weakness, lightheadedness.
* Drug interactions
- Note multiple drug interactions; do not use with other QT prolonging drugs. See full prescribing details.
* Use in specific populations
- Nursing mothers: Discontinue drug or discontinue nursing.
- Pregnancy category: B
- Adjust dose for renal impairment; see above and full prescribing information.
  
